# Generated by Django 5.1.7 on 2025-03-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="место"
                    ),
                ),
                ("time", models.TimeField(verbose_name="время")),
                ("action", models.CharField(max_length=150, verbose_name="действие")),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, verbose_name="периодичность"
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True, null=True, verbose_name="вознаграждение"
                    ),
                ),
                (
                    "time_to_perform",
                    models.PositiveSmallIntegerField(verbose_name="время выполнения"),
                ),
                (
                    "publicity",
                    models.BooleanField(
                        default=False, verbose_name="признак публичности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
