# Generated by Django 5.1.7 on 2025-03-30 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_frequency_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_perform",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="время выполнения",
            ),
        ),
    ]
