# Generated by Django 5.1.7 on 2025-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_options_alter_habit_time_to_perform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(max_length=30, verbose_name="периодичность"),
        ),
    ]
