# Generated by Django 5.1.7 on 2025-03-30 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                default="1,2,3,4,5,6,7", max_length=30, verbose_name="периодичность"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_perform",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=120,
                null=True,
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="время выполнения",
            ),
        ),
    ]
